// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZmqSMo2ZaL6rb_joHE-AMEa2yUhT0_H0',
    appId: '1:318901128431:web:c69519e14abe4d53279f1a',
    messagingSenderId: '318901128431',
    projectId: 'flutter-demo-d6b26',
    authDomain: 'flutter-demo-d6b26.firebaseapp.com',
    storageBucket: 'flutter-demo-d6b26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJsv4hljuaO0U8DNi4Uvi6VfNB_2w7_uE',
    appId: '1:318901128431:android:14069f7a0bee30ce279f1a',
    messagingSenderId: '318901128431',
    projectId: 'flutter-demo-d6b26',
    storageBucket: 'flutter-demo-d6b26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJxT7inkWgQENC-fDh-tJj7HlCQ_t-cEo',
    appId: '1:318901128431:ios:8157208f9897ed77279f1a',
    messagingSenderId: '318901128431',
    projectId: 'flutter-demo-d6b26',
    storageBucket: 'flutter-demo-d6b26.appspot.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJxT7inkWgQENC-fDh-tJj7HlCQ_t-cEo',
    appId: '1:318901128431:ios:8157208f9897ed77279f1a',
    messagingSenderId: '318901128431',
    projectId: 'flutter-demo-d6b26',
    storageBucket: 'flutter-demo-d6b26.appspot.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZmqSMo2ZaL6rb_joHE-AMEa2yUhT0_H0',
    appId: '1:318901128431:web:2cee6140124db44b279f1a',
    messagingSenderId: '318901128431',
    projectId: 'flutter-demo-d6b26',
    authDomain: 'flutter-demo-d6b26.firebaseapp.com',
    storageBucket: 'flutter-demo-d6b26.appspot.com',
  );
}
